### ISSUE TITLE
Unable to patch specific SN: C17Q770VFVH3 due to leading 0 missing in PatchedCrc. 820-4924 board

### ISSUE THREAD

**Issue by Blastsail** [sadponyguerillaboy/Python-Apple-EFI-Patcher-V2#1]
Line 250 creates patchedCrc from patchedFsys4. Using serial number C17Q770VFVH3, patchedCrc should be 0857DC67, but using the patcher tool, it is 857DC67 which then errors out as is it not a valid hex number.

To recreate, use an 820-4924 board then run the patcher program: patcher.py -i 820-4924.bin -o output.bin -s C17Q770VFVH3

This is the only SN I've ever had an issue with and I appreciate all the hard work that has gone into this patcher, Thank you, Blastsail

**Comment by sadponyguerillaboy** [comment]
Can you email me your bios? My email can be found in my github profile. The CRC that is being produced is correct , but it appears that it's just trimming the leading 0x0.

`0x0857DC67` is the same as `857DC67`, python is just trimming the crc.
